services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-project-repository
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - ./.env:/var/www/html/.env
    environment:
      - APP_NAME=StudentProjectRepository
      - APP_ENV=production
      - APP_KEY=${APP_KEY:-base64:CHANGEME}
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-http://localhost:8000}
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - LOG_CHANNEL=stack
      - LOG_LEVEL=error
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
