version: '3.8'

services:
  # Laravel Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-project-repository-dev
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_NAME=StudentProjectRepository
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - SESSION_DRIVER=file
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    networks:
      - app-network
    depends_on:
      - redis

  # Redis for caching
  redis:
    image: redis:alpine
    container_name: student-project-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
